site_name: TA Docs
site_dir: ../site/
pages:
- Home: index.md
- Usage: usage.md
- Documentation:
  - Overview: doc/overview.md
  - Settings: doc/settings.md
  - Animations: doc/animations.md
  - Objects: doc/objects.md
  - Compositions: doc/compositions.md
  - Timelines: doc/timelines.md
- API Docu: doc/api.md
- Tutorial:
  - Setup: tutorial/setup.md
  - Step 01 - Animations: tutorial/step-01.md
  - Step 02 - Objects: tutorial/step-02.md
  - Step 03 - Events: tutorial/step-03.md
  - Step 04 - Timelines: tutorial/step-04.md
- Demos: demos.md
- License: license.md